---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create a directory for cleaning
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ clean_directories }}"
